ARG PYTHON_VERSION=3.10
ARG SERVER_PORT

FROM python:${PYTHON_VERSION}-buster

WORKDIR /usr/share/app

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE ${SERVER_PORT}

ENTRYPOINT [ "python", "main.py" ]
