// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    CompanyLocation: typeof import("./src/components/CompanyLocation.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    System: typeof import("./src/components/System/System.vue")["default"];
    SystemHeader: typeof import("./src/components/System/SystemHeader.vue")["default"];
    TagSelectBlock: typeof import("./src/components/TagSelectBlock.vue")["default"];
  }
}
