// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
    NLayout: typeof import("naive-ui")["NLayout"];
    NLayoutContent: typeof import("naive-ui")["NLayoutContent"];
    NLayoutFooter: typeof import("naive-ui")["NLayoutFooter"];
    NLayoutHeader: typeof import("naive-ui")["NLayoutHeader"];
    NLayoutSider: typeof import("naive-ui")["NLayoutSider"];
    NSpace: typeof import("naive-ui")["NSpace"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheWelcome: typeof import("./src/components/TheWelcome.vue")["default"];
    WelcomeItem: typeof import("./src/components/WelcomeItem.vue")["default"];
  }
}
