// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BubbleBoxHr: typeof import('./src/components/BubbleBox/BubbleBoxHr.vue')['default']
    BubbleBoxUser: typeof import('./src/components/BubbleBox/BubbleBoxUser.vue')['default']
    CompanyDetail: typeof import('./src/components/CompanyDetail/CompanyDetail.vue')['default']
    CompanyPanel: typeof import('./src/components/CompanyPanel/CompanyPanel.vue')['default']
    EducationalExperience: typeof import('./src/components/EducationalExperience/EducationalExperience.vue')['default']
    FilterBar: typeof import('./src/components/SearchAndFilter/FilterBar.vue')['default']
    JobDetail: typeof import('./src/components/JobDetail/JobDetail.vue')['default']
    JobExpectation: typeof import('./src/components/JobExpectation/JobExpectation.vue')['default']
    JobPanel: typeof import('./src/components/JobPanel/JobPanel.vue')['default']
    MailBar: typeof import('./src/components/MailBar/MailBar.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar/NavigationBar.vue')['default']
    ProjectExperience: typeof import('./src/components/ProjectExperience/ProjectExperience.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndFilter: typeof import('./src/components/SearchAndFilter/SearchAndFilter.vue')['default']
    SearchBar: typeof import('./src/components/SearchAndFilter/SearchBar.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience/WorkExperience.vue')['default']
    WybModal: typeof import('./src/components/wyb-modal/wyb-modal.vue')['default']
    WybPopup: typeof import('./src/components/wyb-popup/wyb-popup.vue')['default']
    ZPaging: typeof import('./src/components/z-paging/z-paging.vue')['default']
    ZPagingCell: typeof import('./src/components/z-paging-cell/z-paging-cell.vue')['default']
    ZPagingEmptyView: typeof import('./src/components/z-paging-empty-view/z-paging-empty-view.vue')['default']
    ZPagingLoadMore: typeof import('./src/components/z-paging/components/z-paging-load-more.vue')['default']
    ZPagingRefresh: typeof import('./src/components/z-paging/components/z-paging-refresh.vue')['default']
    ZPagingSwiper: typeof import('./src/components/z-paging-swiper/z-paging-swiper.vue')['default']
    ZPagingSwiperItem: typeof import('./src/components/z-paging-swiper-item/z-paging-swiper-item.vue')['default']
  }
}
